### ISSUE TITLE
Feed - Sort feature for the feed

### ISSUE THREAD

**Issue by vihucode** [kitsain/Kitsain-Frontend-Spring-2024#58]
Parent US: #63

**Comment by katkarin** [comment]
Filtering and sorting now implemented as separate features.

Filtering works so that user can select city, district, sore or some tags, and it will only display posts in the feed with those tags. With sorting, user can select a parameter in which order the posts will be displayed,

Has some bugs with displaying the post, but these will be fixed in a separate issue.
